apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-r1731941967487 
  janus-idp.io/tekton: codegen-r1731941967487
  backstage.io/kubernetes-id: codegen-r1731941967487
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: codegen-r1731941967487
resources: 
- application-dev.yaml