apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-codegen-r1731941967487-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-codegen-r1731941967487-gitops
    spec:  
      serviceAccountName: codegen-r1731941967487-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=codegen-r1731941967487-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/codegen-r1731941967487-notebook -- git clone https://github.com/jrichter-rhtap/codegen-r1731941967487
      restartPolicy: Never