kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen-r1731941967487-imagestream-job-role
  namespace: redhat-ods-applications
rules:
  - verbs:
      - get
      - create
      - list
    apiGroups:
      - "image.openshift.io"
    resources:
      - imagestreams
